### ISSUE TITLE
Add ability to insert UTC timestamps

### ISSUE THREAD

**Issue by mcecode** [lpubsppop01/vscode-auto-timestamp#16] opened 2023-06-14 17:17 UTC
Hello, I'd like to request adding an option that makes this extension insert timestamps in UTC time rather than local time. I'm thinking it could be `lpubsppop01.autoTimeStamp.utc`, which defaults to `false`, so that it's not a breaking change and can be opted in rather than be the default.

If you're open to the idea, I'd be willing to make a pull request to implement it. If not, I'd understand. Either way, thank you for the time you've spent creating and maintaining this extension.

**Comment by lpubsppop01** [comment] 2023-06-18 15:34
Thanks for the feedback and offer of contribution, @mcecode.

I think your request is practical and useful also to others.
I would like to respond to it.

However, I would prefer to add a setting that specifies an arbitrary time zone ID string rather than the UTC flag.
- Although `moment.js` is in maintenance mode, it may not be good, but it seems easier to use `moment-timezone.js`.
- There does not seem to be an ID string that specifies the local time zone, so when a `null` or undefined ID string is specified, the local time zone should be used. This is the default value.

I would be happy if you could implement and PR it,
but please don't take it too hard, as it would be overkill for the purpose of supporting UTC.

If you can't take that much time, I will implement it when I can.

**Comment by mcecode** [comment] 2023-06-19 16:56
I think adding functionality where users can specify an arbitrary time zone is a good idea. I have a suggestion though, would you be open to replacing Moment with [Luxon](https://moment.github.io/luxon) while we're at it? I just thought about it since going forward, [the Moment team already discourages Moment's use](https://momentjs.com/docs/#/-project-status/) and [suggests using other libraries](https://momentjs.com/docs/#/-project-status/recommendations/) such as Luxon.

Additionally, looking at Luxon's documentation, it seems it would be easier to implement this feature with it rather than with Moment since there's a `system` option when [specifying time zones with Luxon](https://moment.github.io/luxon/#/zones?id=specifying-a-zone). So rather than the option's default being `null` or `undefined` and having extra code to handle setting the local time zone with Moment Timezone, it could just be `system` and Luxon would automagically take care of setting the local time zone. Further, aside from IANA time zone identifiers like `America/New_York`, Luxon also supports fixed offset time zones like `UTC+7`, so that could be a good bonus for users like me who prefer to just set fixed offsets rather than specify an IANA identifier.

The downside is, using Luxon would be a breaking change since [format tokens differ between Moment and Luxon](https://moment.github.io/luxon/#/moment?id=basics) ([Moment tokens](https://momentjs.com/docs/#/displaying/format/) vs [Luxon tokens](https://moment.github.io/luxon/#/formatting?id=table-of-tokens)).

I'm still down to make a PR for this whatever direction you want to go with it. I'll start after getting your reply regarding my suggestion.

**Comment by lpubsppop01** [comment] 2023-07-02 13:23
Sorry for the delay in responding.
It is going to be difficult to take time to calm down for a while.
I will get back to you when I am ready to respond, so I hope you will be patient.

**Comment by mcecode** [comment] 2023-07-03 18:42
Hey @lpubsppop01, it's alright. I understand. Take your time.

Just an update though, I had some time today so I implemented the timezone functionality using Luxon, as I suggested, in [my fork](https://github.com/mcecode/vscode-auto-timestamp/tree/luxon-timezone) for personal use. Just tell me when you're ready to get back to this and if you're okay with that direction so I can create a PR. Thanks!

**Comment by lpubsppop01** [comment] 2023-08-11 11:24
Hi, @mcecode.
I'm back. It looks like it will calm down for a while.
Thank you for your thoughtfulness and for creating the forked version.

Your forked version worked well in my environment too.
Timezone support seems to be useful as was expected.

Considering that existing users will also be automatically updated, I thought it would be better to make it work with Moment if there is no Luxon setting but there is Moment setting.
Of course it doesn't support timezone when working with Moment and just only works as before.
I have roughly confirmed the above operation, so I'd like to address it after accepting your PR.
I will also update the Japanese NLS file.

If there is no problem, please create a PR at your convenience.

**Comment by lpubsppop01** [comment] 2023-08-12 02:41
I merged the PR and did the above change for existing users.
It seems to be working well.
I will upload new build to the marketplace later.
Thanks!

**Closed as completed by lpubsppop01** 2023-08-12 02:41 UTC
