### ISSUE TITLE
Settings not appearing in VS Code settings browser

### ISSUE THREAD

**Issue by riley-x** [lpubsppop01/vscode-auto-timestamp#10] opened 2022-02-22 18:39 UTC
If I right click on the extension and click "Extension Settings", VS code finds no settings, which uses the search `@ext:lpubsppop01.vscode-auto-timestamp`. However, settings work fine by manually inputting them in the json as `lpubsppop01.autoTimeStamp.momentFormat` for example. Is there something misconfigured in the package settings?

auto-timestamp: 0.0.4
vscode:

Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-49-generic snap

**Comment by lpubsppop01** [comment] 2022-12-30 08:34
Hi, @riley-x.
Thank you for your feedback, and sorry for the very late reply and check.

I tried to check it in my environment, but I could not reproduce it.
- VS Code version: 1.17.4
- OS: Windows 11, macOS Ventura, Debian 11

It may have been resolved by VS Code.
I'll close it for now.

**Closed as completed by lpubsppop01** 2022-12-30 08:34 UTC
